#!/usr/bin/env python3
"""Remote experiment runner — invoked by fleet scheduler on pods.

This is the Crucible-native entry point that the fleet scheduler launches
on remote nodes via SSH.  It wraps ``run_experiment()`` from
``crucible.runner.experiment`` with a CLI interface matching the arguments
that ``fleet.scheduler.launch_experiment()`` passes.

Usage on pod (auto-generated by scheduler)::

    python3 src/crucible/runner/run_remote.py \
        --backend torch --preset screen \
        --name screen-baseline-v1 --experiment-id 20260322-screen-baseline-v1-abc12345 \
        --tag screen-batch-1 --tag baseline \
        --set MODEL_FAMILY=baseline --set NUM_LAYERS=9
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Make ``crucible`` importable from the synced workspace.
#
# On a pod the layout is:
#   /workspace/parameter-golf/          <- project root
#   /workspace/parameter-golf/src/      <- crucible source
#   /workspace/parameter-golf/src/crucible/runner/run_remote.py  <- this file
#
# So we need ``src/`` on sys.path.
# ---------------------------------------------------------------------------
_SRC_DIR = str(Path(__file__).resolve().parent.parent.parent)
if _SRC_DIR not in sys.path:
    sys.path.insert(0, _SRC_DIR)

from crucible.core.env import load_env_files  # noqa: E402
from crucible.runner.experiment import run_experiment  # noqa: E402


def _parse_overrides(raw: list[str]) -> dict[str, str]:
    config: dict[str, str] = {}
    for item in raw:
        if "=" not in item:
            raise SystemExit(f"Invalid --set value {item!r}; expected KEY=VALUE")
        key, value = item.split("=", 1)
        config[key] = value
    return config


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Crucible remote experiment runner",
    )
    parser.add_argument("--backend", default="torch")
    parser.add_argument("--preset", default="proxy")
    parser.add_argument("--name", required=True)
    parser.add_argument("--experiment-id", required=True)
    parser.add_argument("--timeout", type=int, default=1800)
    parser.add_argument("--tag", action="append", default=[])
    parser.add_argument(
        "--set", dest="overrides", action="append", default=[],
        help="Config override as KEY=VALUE",
    )
    args = parser.parse_args()

    # Resolve project root (two levels up from src/crucible/runner/)
    project_root = Path(__file__).resolve().parent.parent.parent.parent
    load_env_files(project_root)

    config = _parse_overrides(args.overrides)

    result = run_experiment(
        config=config,
        name=args.name,
        experiment_id=args.experiment_id,
        tags=args.tag,
        timeout_seconds=args.timeout,
        backend=args.backend,
        preset=args.preset,
        project_root=project_root,
    )

    status = result.get("status", "unknown")
    bpb = None
    if result.get("result"):
        bpb = result["result"].get("val_bpb")
    summary = f"Status: {status}"
    if bpb is not None:
        summary += f" val_bpb={bpb:.4f}"
    if result.get("result") and result["result"].get("val_loss") is not None:
        summary += f" val_loss={result['result']['val_loss']:.4f}"
    print(summary)


if __name__ == "__main__":
    main()
