"""Jupytext-percent source generation.

This module owns the cell layout for an exported notebook. Each `build_*_cell`
function returns a list of strings, one per source line (no trailing newlines).
`assemble_source` interleaves them with `# %%` / `# %% [markdown]` cell
markers so the output is valid jupytext percent format.

We keep this string-based rather than using `nbformat` directly because:
1. Jupytext source is git-diffable (the whole point of shipping `.py` sources).
2. `.ipynb` is a build artifact — users who want it run `jupytext --to ipynb`.
3. String emission makes unit tests trivial (grep for expected substrings).
"""
from __future__ import annotations

import json
import shlex
from dataclasses import dataclass

from crucible.core.config import ProjectSpec
from crucible.notebook.runtimes import RuntimeProfile


@dataclass
class RenderContext:
    """All the inputs `build_*_cell` needs, collected once."""

    spec: ProjectSpec
    raw_spec: dict                      # raw YAML dict — carries eval_suite + description
    runtime: RuntimeProfile
    preset: str
    variant: str | None
    overrides: dict[str, str]
    crucible_install: str                # pip specifier for crucible itself
    inline_plugins: bool


# ---------------------------------------------------------------------------
# Cell builders — each returns (kind, source_lines)
# kind ∈ {"code", "markdown"}
# ---------------------------------------------------------------------------


def build_header_cell(ctx: RenderContext) -> tuple[str, list[str]]:
    """Opening markdown cell with project + runtime summary."""
    spec = ctx.spec
    desc = (ctx.raw_spec.get("description") or "").strip() or "(no description in spec)"
    lines = [
        f"# {spec.name}",
        "",
        f"**Runtime:** `{ctx.runtime.name}` ({ctx.runtime.gpu_label})",
        f"**Preset:** `{ctx.preset}`",
    ]
    if ctx.variant:
        lines.append(f"**Variant:** `{ctx.variant}`")
    lines += [
        "",
        "**Description:**",
        "",
        desc,
        "",
        f"_Generated by `crucible notebook export`. Source spec: `.crucible/projects/{spec.name}.yaml`._",
    ]
    if ctx.runtime.training_caveats:
        lines += ["", "**Runtime caveats:**", ""]
        lines += [f"- {c}" for c in ctx.runtime.training_caveats]
    return "markdown", lines


def build_install_cell(ctx: RenderContext) -> tuple[str, list[str]]:
    """Install cell: system packages, torch, crucible, spec deps, flash-attn."""
    spec = ctx.spec
    rt = ctx.runtime
    lines = ["# --- Install dependencies ---", "import subprocess"]

    def sh(cmd: str) -> str:
        return f"subprocess.run({_repr(cmd)}, shell=True, check=False)"

    for prelude in rt.shell_prelude:
        if prelude.strip():
            lines.append(sh(prelude))

    if spec.system_packages:
        pkgs = " ".join(shlex.quote(p) for p in spec.system_packages)
        lines.append(sh(f"apt-get -qq install -y {pkgs} >/dev/null 2>&1 || true"))

    # Torch is pre-installed on Colab; only override when spec pins it.
    if spec.install_torch:
        flags = spec.install_flags or ""
        lines.append(sh(f"pip install -q {spec.install_torch} {flags}".strip()))

    # Crucible itself — either git+url or the currently-installed wheel.
    lines.append(sh(f"pip install -q {ctx.crucible_install}".strip()))

    # Runtime extras (accelerate, bitsandbytes, etc.)
    if rt.extra_pip_packages:
        extras = " ".join(shlex.quote(p) for p in rt.extra_pip_packages)
        lines.append(sh(f"pip install -q {extras}"))

    # Spec-declared pip installs.
    if spec.install:
        pkgs = " ".join(shlex.quote(p) for p in spec.install)
        flags = spec.install_flags or ""
        lines.append(sh(f"pip install -q {pkgs} {flags}".strip()))

    # Flash-attn is fragile; install in a try/except with explicit fallback.
    if rt.flash_attn:
        lines += [
            "try:",
            "    import flash_attn  # noqa: F401",
            "    print('flash-attn already installed')",
            "except ImportError:",
            "    _rc = subprocess.run('pip install -q flash-attn --no-build-isolation',",
            "                         shell=True, check=False).returncode",
            "    if _rc != 0:",
            "        print('flash-attn install failed — falling back to SDPA at runtime')",
        ]

    return "code", lines


def build_clone_cell(ctx: RenderContext) -> tuple[str, list[str]]:
    """Clone the project repo into runtime workdir (if spec.repo is set)."""
    spec = ctx.spec
    rt = ctx.runtime
    if not spec.repo:
        return "markdown", [
            "_No `repo:` in project spec — running against the currently-installed Crucible source._",
        ]
    depth_flag = "--depth 1 " if spec.shallow else ""
    clone_cmd = f"git clone {depth_flag}--branch {spec.branch} {spec.repo} {rt.workdir}"
    lines = [
        "# --- Clone project repo ---",
        "import os, subprocess",
        f"WORKDIR = {_repr(rt.workdir)}",
        "if os.path.isdir(WORKDIR) and os.listdir(WORKDIR):",
        "    print(f'{WORKDIR} already populated — reusing.')",
        "else:",
        f"    subprocess.run({_repr(clone_cmd)}, shell=True, check=True)",
        "os.chdir(WORKDIR)",
        "print('cwd:', os.getcwd())",
    ]
    return "code", lines


def build_secrets_cell(ctx: RenderContext) -> tuple[str, list[str]]:
    """Read secrets from Colab userdata (or os.environ) into env dict."""
    rt = ctx.runtime
    spec = ctx.spec
    # Standard keys + whatever the spec forwards.
    keys = list(dict.fromkeys(
        ["WANDB_API_KEY", "HF_TOKEN", "HUGGINGFACE_HUB_TOKEN",
         "ANTHROPIC_API_KEY", "OPENAI_API_KEY"]
        + list(spec.env_forward)
    ))
    lines = [
        "# --- Secrets ---",
        "import os",
        f"_FORWARD_KEYS = {json.dumps(keys)}",
    ]
    if rt.colab_secrets:
        lines += [
            "try:",
            "    from google.colab import userdata",
            "except ImportError:",
            "    userdata = None",
            "for _k in _FORWARD_KEYS:",
            "    if _k in os.environ and os.environ[_k]:",
            "        continue",
            "    if userdata is None:",
            "        continue",
            "    try:",
            "        _v = userdata.get(_k)",
            "    except Exception:",
            "        _v = None",
            "    if _v:",
            "        os.environ[_k] = _v",
        ]
    lines += [
        "_loaded = sorted(k for k in _FORWARD_KEYS if os.environ.get(k))",
        "print('secrets loaded:', _loaded)",
    ]
    return "code", lines


def build_config_cell(ctx: RenderContext) -> tuple[str, list[str]]:
    """Inline the full effective env map (env_set + variant + overrides) for reproducibility."""
    spec = ctx.spec
    env_set = dict(spec.env_set)
    variant_env: dict[str, str] = {}
    if ctx.variant:
        variant_env = dict(spec.variants.get(ctx.variant, {}))
    # Precedence: env_set (base) < variant < --set overrides
    effective = {**env_set, **variant_env, **ctx.overrides}
    lines = [
        "# --- Effective configuration ---",
        f"PROJECT_NAME = {_repr(spec.name)}",
        f"PRESET = {_repr(ctx.preset)}",
        f"VARIANT = {_repr(ctx.variant or '')}",
        f"RUNTIME = {_repr(ctx.runtime.name)}",
        f"EFFECTIVE_ENV = {json.dumps(effective, indent=4, sort_keys=True)}",
        "import os",
        "for _k, _v in EFFECTIVE_ENV.items():",
        "    os.environ[_k] = str(_v)",
        "print(f'{len(EFFECTIVE_ENV)} env var(s) applied')",
        "for _k in sorted(EFFECTIVE_ENV): print(f'  {_k}={EFFECTIVE_ENV[_k]}')",
    ]
    return "code", lines


def build_train_cell(ctx: RenderContext) -> tuple[str, list[str]]:
    """Execute spec.train as a shell command, streaming output inline."""
    spec = ctx.spec
    rt = ctx.runtime
    if not spec.train.strip():
        return "markdown", ["_No `train:` command in spec — skipping training cell._"]
    lines = [
        "# --- Train ---",
        "import os, subprocess, sys, time",
        f"os.makedirs({_repr(rt.default_ckpt_dir)}, exist_ok=True)",
        f"os.environ.setdefault('CRUCIBLE_CKPT_DIR', {_repr(rt.default_ckpt_dir)})",
        f"TRAIN_CMD = {_repr(spec.train.strip())}",
        "print('--- TRAIN CMD ---')",
        "print(TRAIN_CMD)",
        "print('--- running (streamed) ---')",
        "_t0 = time.time()",
        "proc = subprocess.Popen(TRAIN_CMD, shell=True, stdout=subprocess.PIPE,",
        "                        stderr=subprocess.STDOUT, text=True, bufsize=1, env=os.environ)",
        "for _line in proc.stdout:",
        "    sys.stdout.write(_line); sys.stdout.flush()",
        "proc.wait()",
        "print(f'--- done in {time.time()-_t0:.1f}s, exit={proc.returncode} ---')",
        "if proc.returncode != 0:",
        "    raise RuntimeError(f'training exited with code {proc.returncode}')",
    ]
    return "code", lines


def build_eval_cell(ctx: RenderContext) -> tuple[str, list[str]]:
    """Run each eval_suite entry against the newest checkpoint."""
    suite_raw = ctx.raw_spec.get("eval_suite") or []
    if not suite_raw:
        return "markdown", ["_No `eval_suite:` in spec — skipping eval cell._"]
    parsed = []
    for entry in suite_raw:
        if not isinstance(entry, dict) or "script" not in entry:
            continue
        parsed.append({
            "script": str(entry["script"]),
            "args": [str(a) for a in entry.get("args", [])],
        })
    if not parsed:
        return "markdown", ["_Empty `eval_suite:` after parsing — skipping eval cell._"]
    rt = ctx.runtime
    lines = [
        "# --- Evaluation ---",
        "import os, subprocess, json, glob, tempfile",
        f"EVAL_SUITE = {json.dumps(parsed, indent=4)}",
        f"CKPT_DIR = {_repr(rt.default_ckpt_dir)}",
        "ckpts = sorted(glob.glob(os.path.join(CKPT_DIR, '**', '*'), recursive=True),",
        "               key=lambda p: os.path.getmtime(p) if os.path.exists(p) else 0)",
        "ckpts = [c for c in ckpts if os.path.isfile(c)]",
        "if not ckpts:",
        "    print(f'no checkpoint in {CKPT_DIR}; skipping eval')",
        "else:",
        "    latest = ckpts[-1]",
        "    print('evaluating checkpoint:', latest)",
        "    results = {}",
        "    for entry in EVAL_SUITE:",
        "        script = entry['script']",
        "        if not os.path.exists(script):",
        "            print(f'[skip] {script} not found'); continue",
        "        with tempfile.NamedTemporaryFile('r', suffix='.json', delete=False) as _tf:",
        "            out_json = _tf.name",
        "        cmd = ['python3', script, '--checkpoint', latest, '--out', out_json] + entry['args']",
        "        print('>', ' '.join(cmd))",
        "        proc = subprocess.run(cmd, env=os.environ, check=False)",
        "        if proc.returncode == 0 and os.path.exists(out_json):",
        "            try: results[os.path.basename(script)] = json.load(open(out_json))",
        "            except Exception as e: results[os.path.basename(script)] = {'error': str(e)}",
        "        else:",
        "            results[os.path.basename(script)] = {'exit': proc.returncode}",
        "        if os.path.exists(out_json): os.unlink(out_json)",
        "    print(json.dumps(results, indent=2, default=str))",
    ]
    return "code", lines


def build_upload_cell(ctx: RenderContext) -> tuple[str, list[str]]:
    """Optional: upload checkpoint + metrics to HF Hub."""
    rt = ctx.runtime
    lines = [
        "# --- Upload (optional) ---",
        "# Set HF_REPO_ID and HF_TOKEN (via Colab userdata) to enable.",
        "import os",
        "HF_REPO_ID = os.environ.get('HF_REPO_ID', '')",
        "if HF_REPO_ID and os.environ.get('HF_TOKEN'):",
        "    from huggingface_hub import upload_folder",
        f"    upload_folder(repo_id=HF_REPO_ID, folder_path={_repr(rt.default_ckpt_dir)},",
        "                  repo_type='model', token=os.environ['HF_TOKEN'])",
        "    print(f'uploaded {HF_REPO_ID}')",
        "else:",
        "    print('skipping upload (set HF_REPO_ID + HF_TOKEN to enable)')",
    ]
    return "code", lines


# ---------------------------------------------------------------------------
# Assembly
# ---------------------------------------------------------------------------


def assemble_source(ctx: RenderContext) -> str:
    """Render the full jupytext-percent source."""
    header = [
        "# ---",
        "# jupyter:",
        "#   jupytext:",
        "#     text_representation:",
        "#       extension: .py",
        "#       format_name: percent",
        "#       format_version: '1.3'",
        "#       jupytext_version: 1.16.0",
        "#   kernelspec:",
        "#     display_name: Python 3",
        "#     language: python",
        "#     name: python3",
        "# ---",
        "",
    ]
    parts: list[str] = ["\n".join(header)]
    builders = [
        build_header_cell,
        build_install_cell,
        build_clone_cell,
        build_secrets_cell,
        build_config_cell,
        build_train_cell,
        build_eval_cell,
        build_upload_cell,
    ]
    for builder in builders:
        kind, lines = builder(ctx)
        marker = "# %% [markdown]" if kind == "markdown" else "# %%"
        if kind == "markdown":
            flat: list[str] = []
            for line in lines:
                # Multi-line strings (e.g. spec descriptions) arrive as a single
                # entry with embedded '\n'; split so every physical line gets
                # its own '# ' prefix.
                for sub in line.split("\n"):
                    flat.append(f"# {sub}" if sub else "#")
            cell_body = "\n".join(flat)
        else:
            cell_body = "\n".join(lines)
        parts.append(f"{marker}\n{cell_body}\n")
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _repr(value: str) -> str:
    """Python repr() that always produces a single-line string literal."""
    return repr(value)
