"""Format Crucible experiment data as Spider Chat information node content.

Converts experiment configs, hypotheses, and results into structured markdown
suitable for Spider Chat information nodes.
"""
from __future__ import annotations

from typing import Any


def format_experiment_content(
    experiment: dict[str, Any],
    result: dict[str, Any] | None = None,
    best_metric: float | None = None,
    primary_metric: str = "val_bpb",
) -> str:
    """Render experiment as markdown for a Spider Chat information node."""
    parts: list[str] = []

    # Hypothesis
    hypothesis = experiment.get("hypothesis", "")
    if hypothesis:
        parts.append(f"## Hypothesis\n{hypothesis}")

    # Rationale
    rationale = experiment.get("rationale", "")
    if rationale:
        parts.append(f"## Rationale\n{rationale}")

    # Configuration table
    config = experiment.get("config", {})
    if config:
        rows = [f"| {k} | `{v}` |" for k, v in sorted(config.items())]
        table = "| Parameter | Value |\n|-----------|-------|\n" + "\n".join(rows)
        parts.append(f"## Configuration\n{table}")

    # Results
    if result:
        metric_val = result.get(primary_metric)
        is_best = metric_val is not None and best_metric is not None and metric_val == best_metric
        best_marker = " \u2605 best" if is_best else ""

        lines = []
        for k, v in sorted(result.items()):
            if isinstance(v, float):
                line = f"- **{k}**: {v:.4f}"
                if k == primary_metric:
                    line += best_marker
                lines.append(line)
            elif v is not None:
                lines.append(f"- **{k}**: {v}")

        if lines:
            parts.append("## Results\n" + "\n".join(lines))
    else:
        parts.append("## Results\n*Pending*")

    # Generation method
    gen_method = experiment.get("generation_method", "")
    if gen_method:
        parts.append(f"---\n*Generated by: {gen_method}*")

    return "\n\n".join(parts)


def format_finding_content(finding: dict[str, Any]) -> str:
    """Render a research finding as markdown for a Spider Chat information node."""
    parts: list[str] = []

    title = finding.get("title", finding.get("finding", "Untitled finding"))
    parts.append(f"## Finding\n{title}")

    body = finding.get("body", "")
    if body:
        parts.append(body)

    category = finding.get("category", "observation")
    confidence = finding.get("confidence", 0.5)
    parts.append(f"**Category**: {category} | **Confidence**: {confidence:.0%}")

    source_experiments = finding.get("source_experiments", [])
    if source_experiments:
        refs = ", ".join(source_experiments[:5])
        parts.append(f"**Source experiments**: {refs}")

    return "\n\n".join(parts)


def format_review_content(review: dict[str, Any]) -> str:
    """Render experiment review as markdown for a Spider Chat information node."""
    parts: list[str] = []

    parts.append("## Experiment Review")

    recommendation = review.get("recommendation", "unknown")
    icon = {
        "accept": "\u2713 Accepted",
        "rerun": "\u27F3 Needs rerun",
        "investigate": "\u26A0 Investigate",
        "reject": "\u2717 Rejected",
    }.get(recommendation, f"? {recommendation}")
    parts.append(f"**Recommendation**: {icon}")

    for key in ("hypothesis_consistency", "config_sanity", "statistical_significance"):
        val = review.get(key)
        if val is not None:
            parts.append(f"- **{key.replace('_', ' ').title()}**: {val:.0%}")

    reasoning = review.get("reasoning", "")
    if reasoning:
        parts.append(f"\n{reasoning}")

    suspicious = review.get("suspicious_patterns", [])
    if suspicious:
        items = "\n".join(f"- {s}" for s in suspicious)
        parts.append(f"### Suspicious Patterns\n{items}")

    return "\n\n".join(parts)


def crucible_node_type(experiment: dict[str, Any]) -> str:
    """Determine the crucibleType for a Spider Chat node from experiment data."""
    gen = experiment.get("generation_method", "manual")
    if gen in ("manual", "manual_canvas"):
        return "manual"
    if experiment.get("result") is not None:
        return "experiment"
    return "hypothesis"
